#!/usr/bin/env bash
set -Eeuo pipefail

export LC_ALL=C

readonly default_feed_url="https://bazaar.abuse.ch/export/txt/sha256/recent/"
readonly default_list_path="/var/ossec/etc/lists/known-bad-hashes"
readonly default_mode="660"
readonly default_min_entries="2"
readonly default_curl_timeout="120"
readonly default_service="wazuh-manager.service"

script_path=${BASH_SOURCE[0]}
script_parent=$([[ $script_path == */* ]] && printf '%s' "${script_path%/*}" || printf '.')
script_dir=$(cd -- "$script_parent" && pwd -P)
output_file="$script_dir/config.local.conf"
print_only=false
overwrite=false

usage() {
  cat <<'EOF'
Usage: configure.sh [--output PATH] [--overwrite] [--print-discovery]

Discover local Wazuh paths, ownership, and service units, then generate
config.local.conf. The script never modifies list files or restarts services,
and it refuses to replace an existing configuration file without --overwrite.
EOF
}

die() {
  printf 'error: %s\n' "$*" >&2
  exit 1
}

while (($# > 0)); do
  case $1 in
    --output)
      [[ -n ${2-} ]] || die '--output requires a value'
      output_file=$2
      shift 2
      ;;
    --overwrite)
      overwrite=true
      shift
      ;;
    --print-discovery)
      print_only=true
      shift
      ;;
    --help | -h)
      usage
      exit 0
      ;;
    *)
      die "unknown argument: $1"
      ;;
  esac
done

detected_owner=wazuh
if ! id -u wazuh >/dev/null 2>&1; then
  detected_owner=$(id -un 2>/dev/null || printf 'wazuh')
fi

detected_group=wazuh
if ! getent group wazuh >/dev/null 2>&1; then
  detected_group=$(id -gn 2>/dev/null || printf 'wazuh')
fi

detected_list_dir=$(dirname "$default_list_path")
list_dir_exists=no
if [[ -d $detected_list_dir ]]; then
  list_dir_exists=yes
fi

detected_service=$default_service
service_found=no
if command -v systemctl >/dev/null 2>&1; then
  if systemctl cat "$default_service" >/dev/null 2>&1; then
    service_found=yes
  fi
fi

printf 'feed-url=%s\n' "$default_feed_url"
printf 'list-path=%s\n' "$default_list_path"
printf 'list-directory-exists=%s\n' "$list_dir_exists"
printf 'detected-owner=%s\n' "$detected_owner"
printf 'detected-group=%s\n' "$detected_group"
printf 'detected-service=%s (present=%s)\n' "$detected_service" "$service_found"

[[ $print_only == false ]] || exit 0

if [[ $overwrite == false && -e $output_file ]]; then
  die "refusing to replace existing file: $output_file"
fi

read -r -p "Feed URL [$default_feed_url]: " input_feed_url || true
input_feed_url=${input_feed_url%$'\r'}
input_feed_url=${input_feed_url:-$default_feed_url}

read -r -p "CDB list path [$default_list_path]: " input_list_path || true
input_list_path=${input_list_path%$'\r'}
input_list_path=${input_list_path:-$default_list_path}

read -r -p "Owner [$detected_owner]: " input_owner || true
input_owner=${input_owner%$'\r'}
input_owner=${input_owner:-$detected_owner}

read -r -p "Group [$detected_group]: " input_group || true
input_group=${input_group%$'\r'}
input_group=${input_group:-$detected_group}

read -r -p "Mode [$default_mode]: " input_mode || true
input_mode=${input_mode%$'\r'}
input_mode=${input_mode:-$default_mode}

read -r -p "Minimum entries [$default_min_entries]: " input_min_entries || true
input_min_entries=${input_min_entries%$'\r'}
input_min_entries=${input_min_entries:-$default_min_entries}

read -r -p "Curl timeout seconds [$default_curl_timeout]: " input_curl_timeout || true
input_curl_timeout=${input_curl_timeout%$'\r'}
input_curl_timeout=${input_curl_timeout:-$default_curl_timeout}

read -r -p "systemd service unit [$detected_service]: " input_service || true
input_service=${input_service%$'\r'}
input_service=${input_service:-$detected_service}

output_dir=$(dirname "$output_file")
if [[ ! -d $output_dir ]]; then
  mkdir -p "$output_dir" || die "failed to create directory: $output_dir"
fi

write_config() {
  cat <<EOF
# Strict KEY=value file. Generated by configure.sh.
# CUSTOMIZE: URL of the SHA-256 hash feed.
FEED_URL=$input_feed_url
# CUSTOMIZE: Destination path for the Wazuh manager CDB hash list.
LIST_PATH=$input_list_path
# CUSTOMIZE: User ownership for the installed CDB list file.
OWNER=$input_owner
# CUSTOMIZE: Group ownership for the installed CDB list file.
GROUP=$input_group
# CUSTOMIZE: File permission mode for the installed CDB list file.
MODE=$input_mode
# CUSTOMIZE: Minimum number of entries required before installing the new list.
MIN_ENTRIES=$input_min_entries
# CUSTOMIZE: Download timeout in seconds for curl.
CURL_TIMEOUT=$input_curl_timeout
# CUSTOMIZE: systemd service unit restarted after list installation.
RESTART_UNIT=$input_service
# CUSTOMIZE: Optional custom restart command. If set, this overrides RESTART_UNIT.
RESTART_COMMAND=
# CUSTOMIZE: Optional verification command run after RESTART_COMMAND. If set, its failure makes the script exit nonzero.
VERIFY_COMMAND=
EOF
}

if [[ $overwrite == true ]]; then
  (
    umask 077
    write_config >"$output_file"
  )
else
  if ! (
    set -o noclobber
    umask 077
    write_config >"$output_file"
  ); then
    die "refusing to replace existing file: $output_file"
  fi
fi

chmod 600 "$output_file" 2>/dev/null || true

printf 'configuration-written=%s\n' "$output_file"
printf 'next-step: inspect the file, then test with wazuh-hash-list-refresh.sh --config %q --dry-run\n' "$output_file"
